import React, { useState } from 'react';
import { X, Receipt, Plus, Trash2, ArrowDownRight, Sparkles } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { formatCurrency } from '../../data/constants';
import { InvoiceItem } from '../../types';

export const NewInvoiceModal: React.FC = () => {
  const { state, isNewInvoiceModalOpen, setIsNewInvoiceModalOpen, createInvoice, setPreviewInvoice } = useApp();

  const [contactId, setContactId] = useState<string>('');
  const [contactName, setContactName] = useState<string>('');
  const [contactEmail, setContactEmail] = useState<string>('');
  const [dueDate, setDueDate] = useState<string>(
    new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0]
  );
  const [notes, setNotes] = useState<string>('Payment due within 14 days via direct payment link.');
  const [autoPayImmediately, setAutoPayImmediately] = useState<boolean>(false);

  const [items, setItems] = useState<Omit<InvoiceItem, 'id'>[]>([
    { description: 'Strategic Business Retainer Services', quantity: 1, unitPrice: 4500, amount: 4500 },
  ]);

  if (!isNewInvoiceModalOpen) return null;

  const handleAddItem = () => {
    setItems([...items, { description: '', quantity: 1, unitPrice: 1000, amount: 1000 }]);
  };

  const handleItemChange = (index: number, field: string, value: any) => {
    const next = [...items];
    (next[index] as any)[field] = value;
    if (field === 'quantity' || field === 'unitPrice') {
      next[index].amount = next[index].quantity * next[index].unitPrice;
    }
    setItems(next);
  };

  const handleRemoveItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const subtotal = items.reduce((sum, item) => sum + item.amount, 0);
  const total = subtotal; // 0% default sales tax for service contracts

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const cleanName = contactName.trim();
    if (!cleanName || total <= 0) return;

    // Check if the typed client name matches an existing contact in CRM
    const matchedContact = state.contacts.find(
      (c) =>
        c.name.toLowerCase() === cleanName.toLowerCase() ||
        c.company.toLowerCase() === cleanName.toLowerCase()
    );

    const finalContactId = contactId || matchedContact?.id || '';
    const finalEmail =
      contactEmail.trim() ||
      matchedContact?.email ||
      `${cleanName.toLowerCase().replace(/[^a-z0-9]/g, '') || 'client'}@example.com`;

    const formattedItems: InvoiceItem[] = items.map((it, idx) => ({
      ...it,
      id: `item-${Date.now()}-${idx}`,
    }));

    const created = createInvoice(
      {
        contactId: finalContactId,
        contactName: cleanName,
        contactEmail: finalEmail,
        items: formattedItems,
        subtotal,
        taxPct: 0,
        taxAmount: 0,
        total,
        issuedDate: new Date().toISOString().split('T')[0],
        dueDate,
        notes,
        autoGenerated: false,
      },
      autoPayImmediately
    );

    setIsNewInvoiceModalOpen(false);
    setPreviewInvoice(created);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-2xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-xl bg-blue-100 text-blue-700">
              <Receipt className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">Create & Issue Invoice</h3>
              <p className="text-xs text-slate-500">Automatically creates payment link and settlement rule</p>
            </div>
          </div>
          <button
            onClick={() => setIsNewInvoiceModalOpen(false)}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 overflow-y-auto space-y-4 flex-1">
          {/* Client text input & Due date */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="sm:col-span-2">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
                Client / Company Name *
              </label>
              <input
                type="text"
                required
                value={contactName}
                onChange={(e) => {
                  const val = e.target.value;
                  setContactName(val);
                  const matched = state.contacts.find(
                    (c) =>
                      c.name.toLowerCase() === val.toLowerCase() ||
                      c.company.toLowerCase() === val.toLowerCase()
                  );
                  if (matched) {
                    setContactId(matched.id);
                    if (!contactEmail) setContactEmail(matched.email);
                  }
                }}
                placeholder="Type client or company name..."
                className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 text-sm outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 bg-white"
                id="invoice-client-name-input"
              />
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
                Due Date
              </label>
              <input
                type="date"
                required
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 text-sm outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                id="invoice-due-date-input"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
              Client Email Address (for Payment Link)
            </label>
            <input
              type="email"
              value={contactEmail}
              onChange={(e) => setContactEmail(e.target.value)}
              placeholder="e.g. accounting@clientcompany.com"
              className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 text-sm outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 bg-white"
              id="invoice-client-email-input"
            />
          </div>

          {/* Line Items */}
          <div className="pt-2 border-t border-slate-100">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-600">
                Itemized Deliverables
              </span>
              <button
                type="button"
                onClick={handleAddItem}
                className="text-xs text-blue-600 font-bold hover:underline cursor-pointer flex items-center gap-1"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add Line Item</span>
              </button>
            </div>

            <div className="space-y-2">
              {items.map((item, idx) => (
                <div key={idx} className="flex gap-2 items-center">
                  <input
                    type="text"
                    required
                    value={item.description}
                    onChange={(e) => handleItemChange(idx, 'description', e.target.value)}
                    placeholder="Item description..."
                    className="flex-1 px-3 py-1.5 rounded-lg border border-slate-300 text-xs outline-none focus:border-blue-500"
                  />
                  <input
                    type="number"
                    min="1"
                    value={item.quantity}
                    onChange={(e) =>
                      handleItemChange(idx, 'quantity', parseInt(e.target.value) || 1)
                    }
                    className="w-16 px-2 py-1.5 rounded-lg border border-slate-300 text-xs text-center outline-none focus:border-blue-500"
                  />
                  <input
                    type="number"
                    step="50"
                    value={item.unitPrice}
                    onChange={(e) =>
                      handleItemChange(idx, 'unitPrice', parseFloat(e.target.value) || 0)
                    }
                    className="w-24 px-2 py-1.5 rounded-lg border border-slate-300 text-xs text-right font-mono outline-none focus:border-blue-500"
                  />
                  <span className="w-24 text-right font-mono font-bold text-xs text-slate-900">
                    {formatCurrency(item.amount, state.settings.currency)}
                  </span>
                  {items.length > 1 && (
                    <button
                      type="button"
                      onClick={() => handleRemoveItem(idx)}
                      className="p-1 text-slate-400 hover:text-rose-600"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>

            <div className="flex justify-end pt-3 text-base font-black text-slate-900 border-t border-slate-100 mt-3">
              <span>Invoice Total: {formatCurrency(total, state.settings.currency)}</span>
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
              Payment Terms / Notes
            </label>
            <input
              type="text"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs outline-none focus:border-blue-500"
            />
          </div>

          {/* Quick Pay / Settlement Checkbox */}
          <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between">
            <div>
              <span className="text-xs font-bold text-emerald-950 block">
                Simulate Instant Payment Upon Creation
              </span>
              <span className="text-[11px] text-emerald-700">
                Immediately marks invoice as paid and routes {formatCurrency(total, state.settings.currency)} into the 8 accounts.
              </span>
            </div>
            <input
              type="checkbox"
              checked={autoPayImmediately}
              onChange={(e) => setAutoPayImmediately(e.target.checked)}
              className="w-4 h-4 rounded text-emerald-600 focus:ring-emerald-500 cursor-pointer"
            />
          </div>

          <div className="pt-2 flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setIsNewInvoiceModalOpen(false)}
              className="px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={total <= 0}
              className="px-6 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-bold text-sm rounded-xl shadow-xs transition cursor-pointer flex items-center gap-1.5"
            >
              <Receipt className="w-4 h-4" />
              <span>Create Invoice & Payment Link</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
