import React, { useState } from 'react';
import {
  Receipt,
  Plus,
  CheckCircle2,
  Clock,
  ExternalLink,
  Printer,
  Copy,
  Send,
  AlertCircle,
  Filter,
  DollarSign,
  ArrowDownRight,
  Sparkles,
  Trash2,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { formatCurrency } from '../data/constants';
import { Invoice, InvoiceStatus } from '../types';

export const InvoicingView: React.FC = () => {
  const {
    state,
    updateInvoiceStatus,
    deleteInvoice,
    setIsNewInvoiceModalOpen,
    setPreviewInvoice,
    showToast,
  } = useApp();

  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const totalInvoiced = state.invoices.reduce((sum, inv) => sum + inv.total, 0);
  const totalPaid = state.invoices
    .filter((inv) => inv.status === 'paid')
    .reduce((sum, inv) => sum + inv.total, 0);
  const totalPending = state.invoices
    .filter((inv) => inv.status === 'sent')
    .reduce((sum, inv) => sum + inv.total, 0);
  const autoGeneratedCount = state.invoices.filter((inv) => inv.autoGenerated).length;

  const filteredInvoices = state.invoices.filter((inv) => {
    if (statusFilter !== 'all' && inv.status !== statusFilter) return false;
    if (searchQuery.trim() !== '') {
      const q = searchQuery.toLowerCase();
      return (
        inv.invoiceNum.toLowerCase().includes(q) ||
        inv.contactName.toLowerCase().includes(q) ||
        (inv.dealName && inv.dealName.toLowerCase().includes(q))
      );
    }
    return true;
  });

  const handleCopyLink = (inv: Invoice) => {
    const payLink = state.paymentLinks.find((pl) => pl.invoiceId === inv.id);
    const url = payLink?.url || `https://pay.cimpres.app/inv/${inv.invoiceNum.toLowerCase()}`;
    navigator.clipboard.writeText(url);
    showToast(`Copied payment link for ${inv.invoiceNum}`);
  };

  return (
    <div className="space-y-6">
      {/* Header & Automated Invoicing Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            Automated Invoicing & Billing
          </h2>
          <p className="text-sm text-slate-500">
            Invoices generated automatically when deals are Won, with instant payment links and 7-account cash routing.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setIsNewInvoiceModalOpen(true)}
            className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-sm shadow-sm transition active:scale-[0.98] cursor-pointer flex items-center gap-2"
            id="invoicing-create-btn"
          >
            <Plus className="w-4 h-4" />
            <span>Create Invoice</span>
          </button>
        </div>
      </div>

      {/* 4 Financial Invoicing KPI Tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold uppercase text-slate-500 block mb-1">
            Total Invoiced
          </span>
          <div className="text-2xl font-black text-slate-900">
            {formatCurrency(totalInvoiced, state.settings.currency)}
          </div>
          <span className="text-xs text-slate-500 mt-1 block">
            {state.invoices.length} invoices generated
          </span>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold uppercase text-slate-500 block mb-1">
            Collected Revenue
          </span>
          <div className="text-2xl font-black text-emerald-700">
            {formatCurrency(totalPaid, state.settings.currency)}
          </div>
          <span className="text-xs text-emerald-700 font-medium mt-1 block">
            Auto-allocated into reserves
          </span>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold uppercase text-slate-500 block mb-1">
            Pending Receivables
          </span>
          <div className="text-2xl font-black text-amber-800">
            {formatCurrency(totalPending, state.settings.currency)}
          </div>
          <span className="text-xs text-amber-700 font-medium mt-1 block">
            {state.invoices.filter((i) => i.status === 'sent').length} invoices awaiting payment
          </span>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold uppercase text-slate-500 block mb-1">
            Automated Invoices
          </span>
          <div className="text-2xl font-black text-blue-700">
            {autoGeneratedCount} / {state.invoices.length}
          </div>
          <span className="text-xs text-blue-600 font-medium mt-1 block">
            Deal-Won Triggered
          </span>
        </div>
      </div>

      {/* Search & Filter Toolbar */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-2">
          {['all', 'sent', 'paid', 'draft', 'overdue'].map((tab) => (
            <button
              key={tab}
              onClick={() => setStatusFilter(tab)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold uppercase transition cursor-pointer ${
                statusFilter === tab
                  ? 'bg-slate-900 text-white'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {tab === 'all' ? 'All Invoices' : tab}
            </button>
          ))}
        </div>

        <div className="w-full md:w-72">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by invoice # or client..."
            className="w-full px-3.5 py-1.5 rounded-xl border border-slate-200 text-xs focus:border-blue-500 outline-none text-slate-800"
          />
        </div>
      </div>

      {/* Invoices List Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="bg-slate-50/80 border-b border-slate-200 text-slate-500 font-bold uppercase tracking-wider">
                <th className="py-3 px-4">Invoice #</th>
                <th className="py-3 px-4">Client / Recipient</th>
                <th className="py-3 px-4">Deal Source</th>
                <th className="py-3 px-4">Issue / Due Date</th>
                <th className="py-3 px-4 text-right">Amount</th>
                <th className="py-3 px-4 text-center">Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredInvoices.map((inv) => {
                const isPaid = inv.status === 'paid';
                const isSent = inv.status === 'sent';

                return (
                  <tr key={inv.id} className="hover:bg-slate-50/80 transition">
                    <td className="py-3.5 px-4 font-mono font-bold text-slate-900">
                      <div className="flex items-center gap-1.5">
                        <span>{inv.invoiceNum}</span>
                        {inv.autoGenerated && (
                          <span
                            title="Auto-generated on Deal Won"
                            className="px-1.5 py-0.5 rounded text-[9px] font-extrabold bg-blue-50 text-blue-700 border border-blue-200"
                          >
                            AUTO
                          </span>
                        )}
                      </div>
                    </td>

                    <td className="py-3.5 px-4 font-medium text-slate-800">
                      <div>{inv.contactName}</div>
                      <span className="text-[11px] text-slate-400 font-normal">
                        {inv.contactEmail}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 text-slate-600">
                      {inv.dealName ? (
                        <span className="truncate block max-w-[180px]" title={inv.dealName}>
                          {inv.dealName}
                        </span>
                      ) : (
                        <span className="text-slate-400">—</span>
                      )}
                    </td>

                    <td className="py-3.5 px-4 font-mono text-slate-500">
                      <div>Issued: {inv.issuedDate}</div>
                      <div className="text-[11px] text-slate-400">Due: {inv.dueDate}</div>
                    </td>

                    <td className="py-3.5 px-4 text-right font-mono font-black text-sm text-slate-900">
                      {formatCurrency(inv.total, state.settings.currency)}
                    </td>

                    <td className="py-3.5 px-4 text-center">
                      <span
                        className={`inline-block px-2.5 py-1 rounded-full text-[10px] font-extrabold uppercase ${
                          isPaid
                            ? 'bg-emerald-100 text-emerald-800'
                            : isSent
                            ? 'bg-blue-100 text-blue-800'
                            : inv.status === 'overdue'
                            ? 'bg-rose-100 text-rose-800'
                            : 'bg-slate-100 text-slate-700'
                        }`}
                      >
                        {inv.status}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 text-right space-x-2">
                      {/* Mark Paid & Route Funds Button */}
                      {!isPaid && (
                        <button
                          onClick={() => updateInvoiceStatus(inv.id, 'paid', 'Instant Online Transfer')}
                          title="Simulate client payment — automatically routes into 7 accounts"
                          className="px-2.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-xs transition cursor-pointer"
                        >
                          Pay & Allocate
                        </button>
                      )}

                      {/* Preview / Print */}
                      <button
                        onClick={() => setPreviewInvoice(inv)}
                        title="View printable invoice"
                        className="p-1.5 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-200 transition cursor-pointer"
                      >
                        <Printer className="w-4 h-4" />
                      </button>

                      {/* Copy Payment Link */}
                      <button
                        onClick={() => handleCopyLink(inv)}
                        title="Copy direct payment link"
                        className="p-1.5 rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-200 transition cursor-pointer"
                      >
                        <Copy className="w-4 h-4" />
                      </button>

                      {/* Delete */}
                      <button
                        onClick={() => {
                          if (window.confirm(`Delete invoice ${inv.invoiceNum}?`)) {
                            deleteInvoice(inv.id);
                          }
                        }}
                        className="p-1.5 rounded-lg text-rose-500 hover:text-rose-700 hover:bg-rose-50 transition cursor-pointer"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          {filteredInvoices.length === 0 && (
            <div className="p-12 text-center">
              <Receipt className="w-10 h-10 text-slate-300 mx-auto mb-3" />
              <h4 className="text-sm font-bold text-slate-800">No invoices found</h4>
              <p className="text-xs text-slate-500 mt-1">
                Win a deal in the sales pipeline or click &quot;Create Invoice&quot; to issue your first invoice.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
