export type AccountKey = 'C' | 'I' | 'M' | 'P' | 'R' | 'E' | 'S';

export interface AccountInfo {
  key: AccountKey;
  name: string;
  short: string;
  description: string;
  color: string;
  bgLight: string;
  borderLight: string;
  badgeBg: string;
  badgeText: string;
  defaultPct: number;
}

export type AccountBalances = Record<AccountKey, number>;
export type AccountPercentages = Record<AccountKey, number>;

export type ContactType = 'lead' | 'prospect' | 'customer' | 'vip';

export interface ClientContact {
  id: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  type: ContactType;
  ltv: number;
  dealsWon: number;
  onTimePaymentPct: number;
  tags: string[];
  notes: string;
  address?: string;
  createdAt: string;
  lastContactedAt?: string;
}

export type DealStage = 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost';

export interface Deal {
  id: string;
  name: string;
  contactId: string;
  contactName: string;
  value: number;
  stage: DealStage;
  probability: number;
  expectedCloseDate: string;
  notes: string;
  createdAt: string;
  updatedAt: string;
}

export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';

export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
}

export interface Invoice {
  id: string;
  invoiceNum: string;
  contactId: string;
  contactName: string;
  contactEmail: string;
  dealId?: string;
  dealName?: string;
  items: InvoiceItem[];
  subtotal: number;
  taxPct: number;
  taxAmount: number;
  total: number;
  status: InvoiceStatus;
  issuedDate: string;
  dueDate: string;
  paidDate?: string;
  paymentMethod?: string;
  notes?: string;
  autoGenerated?: boolean;
}

export interface PaymentLink {
  id: string;
  code: string;
  title: string;
  contactId?: string;
  contactName: string;
  contactEmail: string;
  amount: number;
  status: 'pending' | 'paid' | 'expired';
  invoiceId?: string;
  url: string;
  createdAt: string;
  paidAt?: string;
}

export type TransactionType = 'cashin' | 'payout' | 'adjust-add' | 'adjust-sub' | 'invoice-payment';

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  note: string;
  date: string;
  accountKey?: AccountKey;
  dist?: Record<AccountKey, number>;
  invoiceId?: string;
  contactName?: string;
}

export type TaskPriority = 'low' | 'medium' | 'high';

export interface Task {
  id: string;
  title: string;
  contactId?: string;
  contactName?: string;
  dealId?: string;
  dueDate: string;
  priority: TaskPriority;
  done: boolean;
  createdAt: string;
}

export interface Quote {
  id: string;
  quoteNum: string;
  clientName: string;
  clientEmail: string;
  title: string;
  items: InvoiceItem[];
  total: number;
  status: 'draft' | 'sent' | 'accepted' | 'rejected';
  validUntil: string;
  createdAt: string;
}

export interface EmailMessage {
  id: string;
  fromName: string;
  fromEmail: string;
  toEmail: string;
  subject: string;
  preview: string;
  body: string;
  time: string;
  unread: boolean;
  tag: 'inbox' | 'sent' | 'deal';
}

export interface Campaign {
  id: string;
  channel: 'sms' | 'whatsapp' | 'email';
  title: string;
  message: string;
  sentCount: number;
  deliveredCount: number;
  clickedCount: number;
  status: 'active' | 'completed' | 'draft';
  date: string;
}

export interface AutomationRule {
  id: string;
  name: string;
  trigger: string;
  action: string;
  active: boolean;
  runCount: number;
}

export interface UserProfile {
  id?: string;
  name: string;
  email: string;
  companyName: string;
  role: string;
  businessType?: string;
  avatarUrl?: string;
  createdAt: string;
}

export interface AppSettings {
  currency: string;
  businessName: string;
  businessEmail: string;
  businessPhone: string;
  businessAddress: string;
  monthlyRentTarget: number;
  monthlyPayrollTarget: number;
}

export interface AppState {
  balances: AccountBalances;
  percentages: AccountPercentages;
  contacts: ClientContact[];
  deals: Deal[];
  invoices: Invoice[];
  paymentLinks: PaymentLink[];
  transactions: Transaction[];
  tasks: Task[];
  quotes: Quote[];
  emails: EmailMessage[];
  campaigns: Campaign[];
  automations: AutomationRule[];
  settings: AppSettings;
}
